// Velocidad de crecimiento por especie (indice interno -> tasa) y curva de
// experiencia de Gen 1 por tasa. Las 4 tasas y sus formulas son las
// publicas/documentadas de toda la vida para esta generacion (Rapida,
// Media Rapida, Media Lenta, Lenta) — no hace falta el pequeno detalle de
// implementacion en ensamblador (tabla de coeficientes empaquetados en
// nibbles) para tener el resultado correcto.
// Fuente de la asignacion por especie: pret/pokeyellow data/pokemon/base_stats/*.asm
export const GROWTH_RATE = {
  "1": "slow",
  "2": "medium_fast",
  "3": "medium_slow",
  "4": "fast",
  "5": "medium_fast",
  "6": "medium_fast",
  "7": "medium_slow",
  "8": "medium_fast",
  "9": "medium_slow",
  "10": "slow",
  "11": "medium_fast",
  "12": "slow",
  "13": "medium_fast",
  "14": "medium_slow",
  "15": "medium_slow",
  "16": "medium_slow",
  "17": "medium_fast",
  "18": "slow",
  "19": "slow",
  "20": "slow",
  "21": "medium_slow",
  "22": "slow",
  "23": "slow",
  "24": "slow",
  "25": "medium_slow",
  "26": "medium_fast",
  "27": "slow",
  "28": "medium_slow",
  "29": "slow",
  "30": "medium_fast",
  "33": "slow",
  "34": "medium_fast",
  "35": "medium_fast",
  "36": "medium_slow",
  "37": "medium_fast",
  "38": "medium_slow",
  "39": "medium_slow",
  "40": "fast",
  "41": "medium_slow",
  "42": "medium_fast",
  "43": "medium_fast",
  "44": "medium_fast",
  "45": "medium_fast",
  "46": "medium_fast",
  "47": "medium_fast",
  "48": "medium_fast",
  "49": "medium_slow",
  "51": "medium_fast",
  "53": "medium_fast",
  "54": "medium_fast",
  "55": "medium_fast",
  "57": "medium_fast",
  "58": "medium_fast",
  "59": "medium_fast",
  "60": "slow",
  "64": "medium_fast",
  "65": "medium_fast",
  "66": "slow",
  "70": "medium_fast",
  "71": "medium_slow",
  "72": "medium_fast",
  "73": "slow",
  "74": "slow",
  "75": "slow",
  "76": "medium_fast",
  "77": "medium_fast",
  "78": "medium_fast",
  "82": "medium_fast",
  "83": "medium_fast",
  "84": "medium_fast",
  "85": "medium_fast",
  "88": "slow",
  "89": "slow",
  "90": "medium_fast",
  "91": "medium_fast",
  "92": "medium_fast",
  "93": "medium_fast",
  "96": "medium_fast",
  "97": "medium_fast",
  "98": "medium_fast",
  "99": "medium_fast",
  "100": "fast",
  "101": "fast",
  "102": "medium_fast",
  "103": "medium_fast",
  "104": "medium_fast",
  "105": "medium_fast",
  "106": "medium_slow",
  "107": "medium_fast",
  "108": "medium_fast",
  "109": "medium_fast",
  "110": "medium_slow",
  "111": "medium_slow",
  "112": "medium_fast",
  "113": "medium_fast",
  "114": "medium_fast",
  "116": "medium_fast",
  "117": "medium_fast",
  "118": "medium_fast",
  "119": "medium_fast",
  "120": "medium_fast",
  "123": "medium_fast",
  "124": "medium_fast",
  "125": "medium_fast",
  "126": "medium_slow",
  "128": "medium_fast",
  "129": "medium_fast",
  "130": "medium_fast",
  "131": "slow",
  "132": "slow",
  "133": "slow",
  "136": "medium_fast",
  "138": "medium_fast",
  "139": "slow",
  "141": "medium_fast",
  "142": "fast",
  "143": "medium_fast",
  "144": "medium_fast",
  "145": "medium_fast",
  "147": "medium_slow",
  "148": "medium_slow",
  "149": "medium_slow",
  "150": "medium_slow",
  "151": "medium_slow",
  "152": "slow",
  "153": "medium_slow",
  "154": "medium_slow",
  "155": "slow",
  "157": "medium_fast",
  "158": "medium_fast",
  "163": "medium_fast",
  "164": "medium_fast",
  "165": "medium_fast",
  "166": "medium_fast",
  "167": "medium_slow",
  "168": "medium_slow",
  "169": "medium_slow",
  "170": "medium_fast",
  "171": "slow",
  "173": "medium_fast",
  "176": "medium_slow",
  "177": "medium_slow",
  "178": "medium_slow",
  "179": "medium_slow",
  "180": "medium_slow",
  "185": "medium_slow",
  "186": "medium_slow",
  "187": "medium_slow",
  "188": "medium_slow",
  "189": "medium_slow",
  "190": "medium_slow"
};

// Experiencia TOTAL acumulada necesaria para llegar al nivel n.
export function totalExpForLevel(rate, n) {
  switch (rate) {
    case "fast": return Math.floor((4 * n ** 3) / 5);
    case "medium_slow": return Math.floor((6 / 5) * n ** 3 - 15 * n ** 2 + 100 * n - 140);
    case "slow": return Math.floor((5 * n ** 3) / 4);
    case "medium_fast":
    default: return n ** 3;
  }
}
