// Nombres y precios de items (ids 1-83). El precio de venta en la tienda es
// la mitad del precio de compra (regla estándar de la saga); items con
// precio de compra 0 no se pueden vender (llaves, medallas, etc).
// Fuente: pret/pokeyellow data/items/names.asm + data/items/prices.asm.
export const ITEM_DATA = {
  1: { name: "MASTER BALL", buyPrice: 0, sellable: false },
  2: { name: "ULTRA BALL", buyPrice: 1200, sellable: true },
  3: { name: "GREAT BALL", buyPrice: 600, sellable: true },
  4: { name: "POKe BALL", buyPrice: 200, sellable: true },
  5: { name: "TOWN MAP", buyPrice: 0, sellable: false },
  6: { name: "BICYCLE", buyPrice: 0, sellable: false },
  7: { name: "?????", buyPrice: 0, sellable: false },
  8: { name: "SAFARI BALL", buyPrice: 1000, sellable: true },
  9: { name: "POKeDEX", buyPrice: 0, sellable: false },
  10: { name: "MOON STONE", buyPrice: 0, sellable: false },
  11: { name: "ANTIDOTE", buyPrice: 100, sellable: true },
  12: { name: "BURN HEAL", buyPrice: 250, sellable: true },
  13: { name: "ICE HEAL", buyPrice: 250, sellable: true },
  14: { name: "AWAKENING", buyPrice: 200, sellable: true },
  15: { name: "PARLYZ HEAL", buyPrice: 200, sellable: true },
  16: { name: "FULL RESTORE", buyPrice: 3000, sellable: true },
  17: { name: "MAX POTION", buyPrice: 2500, sellable: true },
  18: { name: "HYPER POTION", buyPrice: 1500, sellable: true },
  19: { name: "SUPER POTION", buyPrice: 700, sellable: true },
  20: { name: "POTION", buyPrice: 300, sellable: true },
  21: { name: "BOULDERBADGE", buyPrice: 0, sellable: false },
  22: { name: "CASCADEBADGE", buyPrice: 0, sellable: false },
  23: { name: "THUNDERBADGE", buyPrice: 0, sellable: false },
  24: { name: "RAINBOWBADGE", buyPrice: 0, sellable: false },
  25: { name: "SOULBADGE", buyPrice: 0, sellable: false },
  26: { name: "MARSHBADGE", buyPrice: 0, sellable: false },
  27: { name: "VOLCANOBADGE", buyPrice: 0, sellable: false },
  28: { name: "EARTHBADGE", buyPrice: 0, sellable: false },
  29: { name: "ESCAPE ROPE", buyPrice: 550, sellable: true },
  30: { name: "REPEL", buyPrice: 350, sellable: true },
  31: { name: "OLD AMBER", buyPrice: 0, sellable: false },
  32: { name: "FIRE STONE", buyPrice: 2100, sellable: true },
  33: { name: "THUNDERSTONE", buyPrice: 2100, sellable: true },
  34: { name: "WATER STONE", buyPrice: 2100, sellable: true },
  35: { name: "HP UP", buyPrice: 9800, sellable: true },
  36: { name: "PROTEIN", buyPrice: 9800, sellable: true },
  37: { name: "IRON", buyPrice: 9800, sellable: true },
  38: { name: "CARBOS", buyPrice: 9800, sellable: true },
  39: { name: "CALCIUM", buyPrice: 9800, sellable: true },
  40: { name: "RARE CANDY", buyPrice: 4800, sellable: true },
  41: { name: "DOME FOSSIL", buyPrice: 0, sellable: false },
  42: { name: "HELIX FOSSIL", buyPrice: 0, sellable: false },
  43: { name: "SECRET KEY", buyPrice: 0, sellable: false },
  44: { name: "?????", buyPrice: 0, sellable: false },
  45: { name: "BIKE VOUCHER", buyPrice: 0, sellable: false },
  46: { name: "X ACCURACY", buyPrice: 950, sellable: true },
  47: { name: "LEAF STONE", buyPrice: 2100, sellable: true },
  48: { name: "CARD KEY", buyPrice: 0, sellable: false },
  49: { name: "NUGGET", buyPrice: 10000, sellable: true },
  50: { name: "PP UP", buyPrice: 9800, sellable: true },
  51: { name: "POKe DOLL", buyPrice: 1000, sellable: true },
  52: { name: "FULL HEAL", buyPrice: 600, sellable: true },
  53: { name: "REVIVE", buyPrice: 1500, sellable: true },
  54: { name: "MAX REVIVE", buyPrice: 4000, sellable: true },
  55: { name: "GUARD SPEC.", buyPrice: 700, sellable: true },
  56: { name: "SUPER REPEL", buyPrice: 500, sellable: true },
  57: { name: "MAX REPEL", buyPrice: 700, sellable: true },
  58: { name: "DIRE HIT", buyPrice: 650, sellable: true },
  59: { name: "COIN", buyPrice: 10, sellable: true },
  60: { name: "FRESH WATER", buyPrice: 200, sellable: true },
  61: { name: "SODA POP", buyPrice: 300, sellable: true },
  62: { name: "LEMONADE", buyPrice: 350, sellable: true },
  63: { name: "S.S.TICKET", buyPrice: 0, sellable: false },
  64: { name: "GOLD TEETH", buyPrice: 0, sellable: false },
  65: { name: "X ATTACK", buyPrice: 500, sellable: true },
  66: { name: "X DEFEND", buyPrice: 550, sellable: true },
  67: { name: "X SPEED", buyPrice: 350, sellable: true },
  68: { name: "X SPECIAL", buyPrice: 350, sellable: true },
  69: { name: "COIN CASE", buyPrice: 0, sellable: false },
  70: { name: "OAK's PARCEL", buyPrice: 0, sellable: false },
  71: { name: "ITEMFINDER", buyPrice: 0, sellable: false },
  72: { name: "SILPH SCOPE", buyPrice: 0, sellable: false },
  73: { name: "POKe FLUTE", buyPrice: 0, sellable: false },
  74: { name: "LIFT KEY", buyPrice: 0, sellable: false },
  75: { name: "EXP.ALL", buyPrice: 0, sellable: false },
  76: { name: "OLD ROD", buyPrice: 0, sellable: false },
  77: { name: "GOOD ROD", buyPrice: 0, sellable: false },
  78: { name: "SUPER ROD", buyPrice: 0, sellable: false },
  79: { name: "PP UP", buyPrice: 0, sellable: false },
  80: { name: "ETHER", buyPrice: 0, sellable: false },
  81: { name: "MAX ETHER", buyPrice: 0, sellable: false },
  82: { name: "ELIXER", buyPrice: 0, sellable: false },
  83: { name: "MAX ELIXER", buyPrice: 0, sellable: false },
};
